from __future__ import annotations

import json
import os  # noqa: F401 —— 暂保留（历史引用面待清账）；批次20 CI 基线豁免
import shutil
from pathlib import Path

from .apk import extract_apk_payload
from .common import (
    PROJECT_ROOT,
    UpdaterError,
    load_lock,
    remove_tree,
    run,
    write_text,
)
from .environment import require_environment, to_bash_path


CUSTOM_PLUGINS = (
    "dsh-tool-shizuku",
    "dsh-tool-android",
    "dsh-tool-accessibility",
)


def _write_npm_package(path: Path, dependencies: dict[str, str]) -> None:
    write_text(
        path,
        json.dumps(
            {
                "name": "dsh-android-runtime",
                "private": True,
                "description": "Pinned DSH runtime closure for the Android APK",
                "dependencies": dependencies,
            },
            indent=2,
        )
        + "\n",
    )


def install_dsh(devhome: Path, lock: dict) -> None:
    lib = devhome / "dshroot" / "lib"
    remove_tree(lib)
    lib.mkdir(parents=True, exist_ok=True)
    _write_npm_package(
        lib / "package.json",
        {lock["dsh"]["package"]: lock["dsh"]["version"]},
    )
    npm = require_environment(lock["dsh"]["minimum_node_major"])["npm"]
    lockfile = (
        PROJECT_ROOT
        / "compatibility"
        / lock["compatibility_profile"]
        / "package-lock.json"
    )
    if lockfile.is_file():
        shutil.copy2(lockfile, lib / "package-lock.json")
        run(
            [
                npm,
                "ci",
                "--prefix",
                lib,
                "--ignore-scripts",
                "--omit=optional",
                "--no-audit",
                "--no-fund",
            ]
        )
    else:
        run(
            [
                npm,
                "install",
                "--prefix",
                lib,
                "--save-exact",
                "--ignore-scripts",
                "--omit=optional",
                "--no-audit",
                "--no-fund",
                lock["dsh"]["npm_spec"],
            ]
        )


def install_custom_plugins(devhome: Path, lock: dict) -> None:
    profile = devhome / ".dsh" / "profiles" / "web"
    if not profile.is_dir():
        raise UpdaterError(f"profile directory is missing: {profile}")

    package_json = profile / "package.json"
    data = json.loads(package_json.read_text(encoding="utf-8"))
    data.setdefault("dependencies", {})
    for package_name in CUSTOM_PLUGINS:
        data["dependencies"].pop(f"@deepseek-ai/{package_name}", None)
    data["dependencies"]["@deepseek-ai/dsh-tools"] = lock["dsh"]["version"]
    # 批次22 W-B（#P0-①）：patchReload 的值源自上游 base APK 里的
    # dshhome/profiles/web/package.json（仓库侧没有任何模板生成它，本函数是
    # 唯一改写该文件的位置，故在此归一化）。Android 引擎没有 pnpm dev:web，
    # "live" 的 profile 补丁热重载会常驻挂载 cordis-plugin-timer /
    # cordis-plugin-hmr（chokidar watch 轮询）却永远等不到人工编辑 → 纯怠速
    # 耗电。"startup"（上游 ProfilePatchReload 的另一合法值）只在启动时应用
    # 一次补丁文件，行为对 Android 完全等价。
    data.setdefault("dsh", {}).setdefault("profile", {})["patchReload"] = "startup"
    package_json.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")

    npm = require_environment(lock["dsh"]["minimum_node_major"])["npm"]
    run(
        [
            npm,
            "install",
            "--prefix",
            profile,
            "--ignore-scripts",
            "--omit=optional",
            "--no-audit",
            "--no-fund",
        ]
    )

    for package_name in CUSTOM_PLUGINS:
        source = PROJECT_ROOT / "plugins" / package_name
        if not source.is_dir():
            raise UpdaterError(f"custom plugin source is missing: {source}")
        destination = profile / "node_modules" / "@deepseek-ai" / package_name
        remove_tree(destination)
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(source, destination)


def write_build_environment(devhome: Path, lock: dict) -> None:
    env = require_environment(lock["dsh"]["minimum_node_major"])
    node_dir = env["node"].parent
    npm_dir = env["npm"].parent
    path_entries = [
        env["build_tools"],
        env["java_bin"],
        node_dir,
        npm_dir,
    ]
    path = ":".join(to_bash_path(entry) for entry in path_entries) + ":$PATH"
    content = "\n".join(
        [
            "# Generated by tools/dsh_updater/workspace.py",
            f'export PATH="{path}"',
            f'export JAVA_BIN="{to_bash_path(env["java_bin"])}"',
            f'export ANDROID_JAR="{to_bash_path(env["android_jar"])}"',
            f'export APK_TOOLS="{to_bash_path(env["build_tools"])}"',
            "",
        ]
    )
    write_text(devhome / "build" / "env.sh", content)


def write_state(workspace: Path, devhome: Path, base_apk: Path, lock: dict) -> None:
    state = {
        "base_apk": str(base_apk.resolve()),
        "devhome": str(devhome.resolve()),
        "dsh_version": lock["dsh"]["version"],
        "dsh_upstream_tag": lock["dsh"]["upstream_tag"],
        "dsh_upstream_commit": lock["dsh"]["upstream_commit"],
        "compatibility_profile": lock["compatibility_profile"],
    }
    write_text(workspace / "state.json", json.dumps(state, indent=2) + "\n")


def sanitize_home(devhome: Path) -> None:
    dsh_home = devhome / ".dsh"
    for name in (".credentials.yaml", "credentials.yaml"):
        for path in dsh_home.rglob(name):
            if path.is_file():
                path.unlink()


def prepare(workspace: Path, base_apk: Path, force: bool = False) -> Path:
    lock = load_lock()
    workspace = workspace.resolve()
    devhome = workspace / "devhome"
    if workspace.exists() and force:
        remove_tree(workspace)
    workspace.mkdir(parents=True, exist_ok=True)
    if not force and devhome.exists():
        raise UpdaterError(
            f"workspace already exists: {workspace}; pass --force to rebuild it"
        )

    require_environment(lock["dsh"]["minimum_node_major"])
    extract_apk_payload(base_apk.resolve(), devhome)
    install_dsh(devhome, lock)

    from .compatibility import apply_compatibility

    apply_compatibility(devhome, lock["compatibility_profile"])
    install_custom_plugins(devhome, lock)
    # 真机实证（2026-09-13）：insert（home patch 语境）从 dshhome/profiles/web/
    # 解析，第三方包必须双树物化。必须排在 install_custom_plugins 之后（npm
    # install 整理 profile 依赖树后再落位，此后无任何清树操作）。
    from .compatibility import apply_profile_vendor_overlay

    apply_profile_vendor_overlay(devhome)
    sanitize_home(devhome)
    write_build_environment(devhome, lock)
    write_state(workspace, devhome, base_apk, lock)
    return devhome


def refresh(workspace: Path) -> Path:
    lock = load_lock()
    workspace = workspace.resolve()
    devhome = workspace / "devhome"
    if not devhome.is_dir():
        raise UpdaterError(f"workspace is not prepared: {workspace}")

    require_environment(lock["dsh"]["minimum_node_major"])
    install_dsh(devhome, lock)

    from .compatibility import apply_compatibility

    apply_compatibility(devhome, lock["compatibility_profile"])
    install_custom_plugins(devhome, lock)
    # 真机实证（2026-09-13）：insert（home patch 语境）从 dshhome/profiles/web/
    # 解析，第三方包必须双树物化。必须排在 install_custom_plugins 之后（npm
    # install 整理 profile 依赖树后再落位，此后无任何清树操作）。
    from .compatibility import apply_profile_vendor_overlay

    apply_profile_vendor_overlay(devhome)
    sanitize_home(devhome)
    write_build_environment(devhome, lock)
    return devhome
