"""Contract: the bundled dsh-attachment-local tolerates fsync EINVAL/EROFS.

Device fact (Honor BKQ-AN10 / Android 17): the filesystem root "/" is erofs
mounted read-only, and fsync(2) on it fails with EINVAL. The attachment store
walks from DSH_HOME up to "/" calling syncDirectory() per level, so an
unpatched module fails the entire image-attachment write path (read_image /
android_see / android_vscreen_see) even though android_screenshot can still
drop a PNG on disk.

Two independent guards live here:

1. Shape/balance checks on the module inside the shipped base APK payload.
2. Behavioural check: the extracted syncDirectory is exercised with a stubbed
   open() whose handle rejects sync() with EINVAL / EROFS / ENOTSUP the way
   this device does, and must resolve instead of throwing.

android-app/DeepSeekHarness.apk is a git-ignored build input regenerated by the
build pipeline, so the payload can silently revert to the upstream module.
tools/patch_base_apk_attachment.py is the preflight that re-applies the fix; run
it via "python .local/b47_build.py all" before this test if it fails.
"""

from __future__ import annotations

import io
import re
import shutil
import subprocess
import tempfile
import unittest
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASE_APK = ROOT / "android-app" / "DeepSeekHarness.apk"
PAYLOAD_NAME = "assets/payload.zip"
MODULE_NAME = (
    "dshroot/lib/node_modules/@deepseek-ai/dsh-attachment-local/lib/index.js"
)

# Codes a read-only / unusual Android mount can return for a directory fsync.
TOLERATED = ("EINVAL", "EROFS", "ENOTSUP", "EOPNOTSUPP", "EACCES", "EPERM")

SYNC_FN_RE = re.compile(
    r"async function syncDirectory\(path\) \{(?P<body>.*?)\n\}",
    re.DOTALL,
)

HARNESS_TEMPLATE = """
class RejectingHandle {
  constructor(code) { this.code = code; }
  async sync() { const e = new Error('simulated'); e.code = this.code; throw e; }
  async close() {}
}
async function run(code, openCode) {
  const constants = { O_RDONLY: 0 };
  const open = async (path, flags) => {
    if (openCode) { const e = new Error('simulated open'); e.code = openCode; throw e; }
    return new RejectingHandle(code);
  };
  const fn = async function syncDirectory(path) {
__BODY__
  };
  try { await fn('/'); return 'resolved'; }
  catch (err) { return 'threw:' + (err && err.code); }
}
const results = [];
for (const code of __CODES__) {
  results.push(code + '=' + (await run(code, null)));
}
results.push('openEACCES=' + (await run(null, 'EACCES')));
results.push('openEPERM=' + (await run(null, 'EPERM')));
console.log(results.join(' '));
"""


class AttachmentFsyncEinvAlTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        if not BASE_APK.exists():
            raise unittest.SkipTest(f"base APK missing: {BASE_APK}")
        with zipfile.ZipFile(BASE_APK) as apk:
            payload = apk.read(PAYLOAD_NAME)
        with zipfile.ZipFile(io.BytesIO(payload)) as zpay:
            cls.module_text = zpay.read(MODULE_NAME).decode("utf-8")

    def _body(self) -> str:
        match = SYNC_FN_RE.search(self.module_text)
        self.assertIsNotNone(match, "syncDirectory not found in bundled module")
        return match.group("body")

    # -- 1. shape guards -------------------------------------------------

    def test_module_tolerates_readonly_fs_fsync_errors(self) -> None:
        for code in ("EINVAL", "EROFS", "ENOTSUP", "EOPNOTSUPP"):
            self.assertIn(
                'error.code === "' + code + '"',
                self.module_text,
                f"bundled attachment module must tolerate fsync {code}",
            )

    def test_module_still_tolerates_permission_errors(self) -> None:
        for code in ("EACCES", "EPERM"):
            self.assertIn('error.code === "' + code + '"', self.module_text)

    def test_sync_directory_block_is_brace_balanced(self) -> None:
        body = self._body()
        self.assertEqual(
            body.count("{"),
            body.count("}"),
            "syncDirectory braces must balance or the module will not parse",
        )

    def test_sync_failure_does_not_rethrow_tolerated_codes(self) -> None:
        body = self._body()
        self.assertIn("throw error;", body)
        self.assertIn("!(", body, "sync catch must negate the tolerated set")

    def test_payload_module_parses_as_javascript(self) -> None:
        node = shutil.which("node")
        if node is None:
            self.skipTest("node not available for parse check")
        with tempfile.TemporaryDirectory() as temp:
            target = Path(temp) / "index.js"
            target.write_text(self.module_text, encoding="utf-8")
            proc = subprocess.run(
                [node, "--check", str(target)], capture_output=True, text=True
            )
        self.assertEqual(
            proc.returncode,
            0,
            f"bundled module must parse: {proc.stderr.strip()[:400]}",
        )

    # -- 2. behavioural guard -------------------------------------------

    def test_sync_directory_survives_device_like_fsync_failures(self) -> None:
        node = shutil.which("node")
        if node is None:
            self.skipTest("node not available for behavioural check")

        body = self._body()
        body = re.sub(r"/\*.*?\*/", "", body, flags=re.DOTALL)
        body = body.replace('process.platform === "win32"', "false")
        body = "\n".join("  " + line for line in body.splitlines())

        codes = "[" + ", ".join("'" + c + "'" for c in TOLERATED) + "]"
        script_src = HARNESS_TEMPLATE.replace("__BODY__", body).replace(
            "__CODES__", codes
        )

        with tempfile.TemporaryDirectory() as temp:
            script = Path(temp) / "m.mjs"
            script.write_text(script_src, encoding="utf-8")
            proc = subprocess.run(
                [node, str(script)], capture_output=True, text=True
            )
        self.assertEqual(
            proc.returncode, 0, f"harness failed: {proc.stderr.strip()[:400]}"
        )
        out = proc.stdout.strip()
        for code in TOLERATED:
            self.assertIn(
                code + "=resolved",
                out,
                f"syncDirectory must swallow {code}; got: {out}",
            )
        self.assertIn("openEACCES=resolved", out)


if __name__ == "__main__":
    unittest.main()
