"""Preflight: keep the fsync durability fix inside the base APK payload.

Why this exists
---------------
`android-app/DeepSeekHarness.apk` (BASE_APK) is a git-ignored build input that
is **regenerated by the Android build pipeline**. Any hand-patch applied to the
`dsh-attachment-local` copy inside its `assets/payload.zip` is therefore
silently lost on the next rebuild, and the staged runtime on the device reverts
to the unpatched module.

What breaks when it reverts
---------------------------
`ensureDurableDirectory()` walks from `DSH_HOME` up to the filesystem root and
fsyncs each level. This device's `/` is **erofs mounted read-only**, where
`fsync(2)` fails with `EINVAL`. The shipped catch only tolerates
`EACCES`/`EPERM`, so the whole image-attachment write path dies with
`EINVAL: invalid argument, fsync` -> `read_image`, `android_see` and
`android_vscreen_see` all fail even though `android_screenshot` still writes a
PNG file.

What this script does
---------------------
Idempotently rewrites `assets/payload.zip` inside BASE_APK so the bundled
`dsh-attachment-local/lib/index.js` tolerates `EINVAL` / `EROFS` / `ENOTSUP`
/`EOPNOTSUPP` in addition to `EACCES` / `EPERM`. The replacement is
brace-balanced, so the module still parses.

It is safe to run on every build: when the payload is already patched the
function returns without touching the file.
"""

from __future__ import annotations

import io
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASE_APK = ROOT / "android-app" / "DeepSeekHarness.apk"
PAYLOAD_NAME = "assets/payload.zip"
MODULE_NAME = (
    "dshroot/lib/node_modules/@deepseek-ai/dsh-attachment-local/lib/index.js"
)

# A recognition token: the module-level function signature is upstream-stable.
FUNCTION_ANCHOR = "async function syncDirectory(path) {"
MARKER = 'error.code === "EINVAL"'

# The block this script replaces (upstream form, CRLF inside payload.zip).
OLD_BLOCK = (
    "\ttry {\r\n"
    "\t\tawait handle.sync();\r\n"
    "\t} finally {\r\n"
    "\t\tawait handle.close();\r\n"
    "\t}"
)
NEW_BLOCK = (
    "\ttry {\r\n"
    "\t\tawait handle.sync();\r\n"
    "\t} catch (error) {\r\n"
    "\t\t/* Android: a directory handle can open successfully yet still reject\r\n"
    "\t\t   fsync. The filesystem root (\"/\") is erofs mounted read-only and\r\n"
    "\t\t   reports EINVAL; some FUSE / sdcardfs mounts report ENOTSUP. Same\r\n"
    "\t\t   rationale as the unopenable level above: synced data already lives\r\n"
    "\t\t   below this level, and durability of that prefix is owned by the OS,\r\n"
    "\t\t   so skip it instead of failing the whole attachment write. */\r\n"
    "\t\tif (!(error && (error.code === \"EINVAL\" || error.code === \"EROFS\""
    " || error.code === \"ENOTSUP\" || error.code === \"EOPNOTSUPP\""
    " || error.code === \"EACCES\" || error.code === \"EPERM\"))) throw error;\r\n"
    "\t} finally {\r\n"
    "\t\tawait handle.close();\r\n"
    "\t}"
)


def patch_module(text: str) -> tuple[str, bool]:
    """Return (text, changed). Idempotent; raises on an unexpected shape."""
    if MARKER in text and FUNCTION_ANCHOR in text:
        return text, False
    if OLD_BLOCK not in text:
        raise RuntimeError(
            "unexpected dsh-attachment-local shape: neither the patched form nor "
            "the upstream sync block was found; upstream layout probably changed"
        )
    return text.replace(OLD_BLOCK, NEW_BLOCK, 1), True


def patch_base_apk(path: Path = BASE_APK, *, verbose: bool = True) -> bool:
    """Patch BASE_APK in place. Returns True when the payload was rewritten."""
    if not path.exists():
        raise FileNotFoundError(f"base APK not found: {path}")

    with zipfile.ZipFile(path) as apk:
        payload = apk.read(PAYLOAD_NAME)
        apk_entries = [
            (item, apk.read(item.filename)) for item in apk.infolist()
        ]

    with zipfile.ZipFile(io.BytesIO(payload)) as zpay:
        names = zpay.namelist()
        if MODULE_NAME not in names:
            raise RuntimeError(f"{MODULE_NAME} is missing from {PAYLOAD_NAME}")
        module_text = zpay.read(MODULE_NAME).decode("utf-8")

    patched_text, changed = patch_module(module_text)
    if not changed:
        if verbose:
            print(f"[attachment-preflight] already patched: {path.name}")
        return False

    new_payload = io.BytesIO()
    with zipfile.ZipFile(io.BytesIO(payload)) as zpay, zipfile.ZipFile(
        new_payload, "w", zipfile.ZIP_DEFLATED
    ) as zout:
        for item in zpay.infolist():
            data = zpay.read(item.filename)
            if item.filename == MODULE_NAME:
                data = patched_text.encode("utf-8")
            zout.writestr(item, data)

    tmp = path.with_suffix(".apk.tmp-payload")
    try:
        with zipfile.ZipFile(tmp, "w") as zout:
            for item, data in apk_entries:
                if item.filename == PAYLOAD_NAME:
                    data = new_payload.getvalue()
                zout.writestr(item, data)
        tmp.replace(path)
    finally:
        if tmp.exists():
            tmp.unlink()

    if verbose:
        print(f"[attachment-preflight] patched {MODULE_NAME} inside {path.name}")
    return True


def main(argv: list[str]) -> int:
    target = Path(argv[1]) if len(argv) > 1 else BASE_APK
    changed = patch_base_apk(target)
    print("changed" if changed else "unchanged")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
